// Update payload flowing from clients to the hub describing edits or console changes.
namespace NetAppForVika.Shared.Dtos;

/// <summary>
/// Announces an incremental document change together with new console output for the group.
/// </summary>
/// <param name="SessionId">The collaborative room the change belongs to.</param>
/// <param name="EditorDelta">Diff-style JSON produced by the collaborative editor when text changes.</param>
/// <param name="OutputAppend">Optional stdout snippet generated by running code locally.</param>
/// <param name="Author">Display name of the client who issued the change for attribution.</param>
public sealed record ClubSessionUpdateDto(
    string SessionId,
    string EditorDelta,
    string? OutputAppend,
    string Author);
