// EF Core entity capturing the summary of a visualised algorithm run for analytics dashboards.
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetAppForVika.Shared.Enums;

namespace NetAppForVika.Server.Models;

/// <summary>
/// Stores metadata about an algorithm simulation so the analytics charts can aggregate usage trends.
/// </summary>
public sealed class AlgorithmRun
{
    /// <summary>
    /// Primary identifier generated by the database for easy lookups.
    /// </summary>
    [Key]
    public Guid Id { get; set; }

    /// <summary>
    /// High-level family of the algorithm (sorting, pathfinding, graph traversal).
    /// </summary>
    public AlgorithmFamily Family { get; set; }

    /// <summary>
    /// Concrete algorithm name stored to drive per-algorithm statistics.
    /// </summary>
    [MaxLength(64)]
    public string AlgorithmName { get; set; } = string.Empty;

    /// <summary>
    /// Seed used during generation to reproduce deterministic graph layouts in WebGL visualisations.
    /// </summary>
    public int Seed { get; set; }

    /// <summary>
    /// Duration in milliseconds for the simulation so we can benchmark improvements over time.
    /// </summary>
    public double DurationMilliseconds { get; set; }

    /// <summary>
    /// Stores the number of steps used in the visualisation so chart.js can plot complexity curves.
    /// </summary>
    public int StepCount { get; set; }

    /// <summary>
    /// Timestamp captured in UTC to enable timeline analytics.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>
    /// Optional JSON payload containing interesting metric aggregates for later data mining.
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? MetricsJson { get; set; }
}
